dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: decide-ci-serortagu
  strategy: git
  api_key:
    secure: aCjRThO0zAuaBvBh9ChCgCsqf2sAIdMiaI/jUxy8B+OC0C9nQ92gEvU4+skS+xbGTDLQWxnZCD2VRPxnM6DOr2eCFvxNJ51MrppYstjhn6PKYPm0d+B+AiWfiMR+MprbyUeheF2tQ9FglK7GzroU3RmyhZ5Y6GSdvICgP4+C4V2L8IqYzhlgXykHRrlGCcAEHALvzJdpoM6He3mXNwrgjAOFepSMRwCHJh7XNSGNF3EyDacHHq+fn3yaDj/nhuKrmJohp+UPiE6iNhPh1Wm0RUsf61JVQ1wx4SMYiCLwY7y0h1/A+uiEKOMOc4JOMMKy0DinmRw07YsPD6Dz+03dhe6tFnc0yDMYtDidJtUZqQITGNkXNY+VQ8W79ILbSo4hNBxquyjEbgX5S73wz+XPSx3MkVd/WUmngWkYA9VF3Zq9Ilm0vOqQDUPURCfYWhS4xkI/IdhROP/xUQXK2X2WGUl4IHdnA+04dE/R0ft/XxT7X6qmgYEm34JvL7o5pwLO4lfDbwYoyrwn4XIvfY06YmsziipKT+qS3AWhs4ASfZq5RcWZXKuH79lrJZRhqRq+urUHuDND9oO29M+o1nUvFpBHxqIZFPO18sKzERqTXFDiLyr24pPrDKEqpxNe4npLko+ec9j0URY9D/taV+qiFqBw2iq+OQ7L9Y7M9BQTvwI=
